package takhosted

import (
	"context"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"errors"
	"fmt"
	"log/slog"
	"time"
)

// CertKeeper asks the operator for a PHONE's certificate, as IdentityKeeper does
// for the Hub's own.
//
// # Why this is a second type and not a method on IdentityKeeper
//
// IdentityKeeper holds long-lived state: one certificate per tenant, renewed
// before expiry, cached in memory because every CoT connection needs it. An
// enrolment is the opposite -- one certificate for one person, collected once and
// never held. Sharing the cache would mean keeping customers' private keys in Hub
// memory for as long as the process lives, which is precisely what we do not want.
//
// # Why the private key does not live here
//
// The key is generated by the caller, travels with the enrolment stash, and is
// destroyed when the package is claimed. This type only moves CSRs and
// certificates, so a reader can see at a glance that it cannot leak a key.
//
// # The operator is still the only thing that can sign
//
// Same boundary as everywhere else in this package: the tenant's CA key is the
// operator's and the Hub has never seen it. The Hub can ask for a certificate
// naming a username; it cannot mint one, and it cannot ask for a subject of its
// choosing -- the operator discards the CSR's subject and issues spec.Username.
type CertKeeper struct {
	client *Client
	log    *slog.Logger
}

// NewCertKeeper wires one up.
func NewCertKeeper(c *Client, log *slog.Logger) *CertKeeper {
	if log == nil {
		log = slog.Default()
	}
	return &CertKeeper{client: c, log: log}
}

// ErrCertPending means the operator has not signed yet. Normal: it reconciles on
// a ticker, so a fresh request waits a few seconds.
var ErrCertPending = errors.New("takhosted: certificate is pending issuance")

// ErrCertDenied is terminal and carries a reason worth showing a customer.
var ErrCertDenied = errors.New("takhosted: certificate was denied")

// eudCertName is the object name for one person's enrolment.
//
// Deterministic, so a retry lands on the same object rather than queueing a
// second signature, and built from the opaque instance label rather than the
// tenant id -- object names are visible in the namespace and the label leaks
// nothing about who the customer is. The username is in it because a tenant
// enrols several people and each needs its own request.
func eudCertName(label, username string) string {
	return "eud-" + label + "-" + username
}

// CertMaterial is what a signed request yields.
type CertMaterial struct {
	CertPEM   string
	CACertPEM string
	Serial    string
	NotAfter  time.Time
}

// NewEUDKey generates the key and CSR for one enrolment.
//
// RSA 2048, not the P-256 the Hub uses for its own identity. This key ends up in
// a PKCS#12 inside an ATAK truststore, and that ecosystem is RSA by convention --
// the same reasoning that made the tenant CA RSA. The subject is set for
// readability only; the operator discards it and issues spec.Username.
func NewEUDKey(username string) (csrPEM, keyPEM []byte, err error) {
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return nil, nil, fmt.Errorf("takhosted: generate enrolment key: %w", err)
	}
	der, err := x509.CreateCertificateRequest(rand.Reader, &x509.CertificateRequest{
		Subject: pkix.Name{CommonName: username},
	}, key)
	if err != nil {
		return nil, nil, fmt.Errorf("takhosted: create enrolment CSR: %w", err)
	}
	csrPEM = pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE REQUEST", Bytes: der})
	keyPEM = pem.EncodeToMemory(&pem.Block{
		Type:  "RSA PRIVATE KEY",
		Bytes: x509.MarshalPKCS1PrivateKey(key),
	})
	return csrPEM, keyPEM, nil
}

// Request asks for a certificate for one username, replacing any request already
// outstanding for it.
//
// The replace is deliberate. A new enrolment means a new key, so a certificate
// signed for the PREVIOUS key is of no use to anybody -- leaving it would hand the
// next collection a certificate whose key has been thrown away, which is the
// stale-pair bug IdentityKeeper has to detect and recover from. Deleting first
// means the only request that can ever be collected is the current one.
func (k *CertKeeper) Request(ctx context.Context, label, username string, csrPEM []byte) error {
	if k == nil || k.client == nil {
		return errors.New("takhosted: certificate keeper has no client")
	}
	name := eudCertName(label, username)
	if err := k.client.DeleteCertRequest(ctx, name); err != nil && !IsNotFound(err) {
		return fmt.Errorf("takhosted: clearing a previous enrolment request: %w", err)
	}
	err := k.client.CreateCertRequest(ctx, TakCertificateRequest{
		Metadata: objectMeta{
			Name: name,
			Labels: map[string]string{
				"app.kubernetes.io/name":  "meshsat-hub",
				"tak.meshsat.net/label":   label,
				"tak.meshsat.net/purpose": PurposeEUD,
			},
		},
		Spec: CertReqSpec{
			Label:    label,
			Purpose:  PurposeEUD,
			Username: username,
			CSRPEM:   string(csrPEM),
		},
	})
	if err != nil {
		return fmt.Errorf("takhosted: asking for an enrolment certificate: %w", err)
	}
	k.log.Info("takhosted: asked for an enrolment certificate", "label", label, "username", username)
	return nil
}

// Collect returns the signed certificate, ErrCertPending, or ErrCertDenied.
func (k *CertKeeper) Collect(ctx context.Context, label, username string) (CertMaterial, error) {
	if k == nil || k.client == nil {
		return CertMaterial{}, errors.New("takhosted: certificate keeper has no client")
	}
	req, err := k.client.GetCertRequest(ctx, eudCertName(label, username))
	switch {
	case IsNotFound(err):
		// Nothing was asked for, or somebody removed it. Not pending: pending
		// implies waiting will help, and here it will not.
		return CertMaterial{}, fmt.Errorf("takhosted: no enrolment request for %q", username)
	case err != nil:
		return CertMaterial{}, fmt.Errorf("takhosted: reading the enrolment request: %w", err)
	}

	switch req.Status.Phase {
	case CertIssued:
		if req.Status.CertPEM == "" || req.Status.CACertPEM == "" {
			// Issued without material is not something to paper over: a package
			// built from it would be missing its trust anchor and fail on the
			// handset with nothing to explain it.
			return CertMaterial{}, fmt.Errorf(
				"takhosted: enrolment for %q is Issued but carries no certificate or CA", username)
		}
		leaf, err := parseOneCert(req.Status.CertPEM)
		if err != nil {
			return CertMaterial{}, fmt.Errorf("takhosted: issued enrolment certificate does not parse: %w", err)
		}
		if leaf.Subject.CommonName != username {
			// The operator forces this, so a mismatch means the object was
			// tampered with or answers a different request. Either way the
			// package would authenticate as somebody else, or as nobody.
			return CertMaterial{}, fmt.Errorf(
				"takhosted: enrolment certificate names %q, not %q",
				leaf.Subject.CommonName, username)
		}
		return CertMaterial{
			CertPEM:   req.Status.CertPEM,
			CACertPEM: req.Status.CACertPEM,
			Serial:    req.Status.Serial,
			NotAfter:  leaf.NotAfter,
		}, nil

	case CertDenied:
		return CertMaterial{}, fmt.Errorf("%w: %s", ErrCertDenied, req.Status.Message)

	default:
		return CertMaterial{}, ErrCertPending
	}
}

// Discard removes a collected or abandoned request.
//
// Called after a successful claim and when an enrolment is cancelled. Leaving
// these behind accumulates one object per person per enrolment, each holding a
// certificate -- public, but still a growing pile of objects in a namespace with a
// quota.
func (k *CertKeeper) Discard(ctx context.Context, label, username string) error {
	if k == nil || k.client == nil {
		return errors.New("takhosted: certificate keeper has no client")
	}
	if err := k.client.DeleteCertRequest(ctx, eudCertName(label, username)); err != nil && !IsNotFound(err) {
		return fmt.Errorf("takhosted: discarding an enrolment request: %w", err)
	}
	return nil
}
