apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secrets
  namespace: meshsat-hub
  labels:
    app.kubernetes.io/name: redis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: redis-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: ci-no/apps/meshsat-hub/redis
        property: REDIS_PASSWORD
