apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecrets.yaml
  - cluster-meshsat-hub-main.yaml
  - database-hawkbit.yaml
  - database-meshsat-hub.yaml
  - scheduledbackup.yaml
  - backup-unwedge.yaml
  - networkpolicy.yaml
