package api

import (
	"crypto/rand"
	"encoding/hex"
	"log/slog"
	"net/http"
	"os"
	"strings"

	"github.com/meshsat/meshsat-hub/internal/store"
)

// SecurityStatus represents the current service authentication state.
type SecurityStatus struct {
	NATSMQTTAuth    bool   `json:"nats_mqtt_auth"`         // NATS MQTT has password configured
	NATSLeafAuth    bool   `json:"nats_leaf_auth"`         // NATS leafnode has token
	RedisAuth       bool   `json:"redis_auth"`             // Redis has password
	StunnelMTLS     bool   `json:"stunnel_mtls"`           // stunnel has client cert verification
	AutoGenerated   bool   `json:"auto_generated"`         // passwords were auto-generated
	SecretsFilePath string `json:"secrets_file,omitempty"` // path to secrets file (admin info)
}

// SecuritySettingsHandler provides REST endpoints for service security status.
type SecuritySettingsHandler struct {
	store store.Store
}

// NewSecuritySettingsHandler creates a new security settings handler.
func NewSecuritySettingsHandler(s store.Store) *SecuritySettingsHandler {
	return &SecuritySettingsHandler{store: s}
}

// GetSecurityStatus returns the current service authentication state.
// @Summary Get service security status
// @Description Shows which internal services have authentication configured.
// @Tags settings
// @Produce json
// @Success 200 {object} SecurityStatus
// @Router /api/settings/security [get]
func (h *SecuritySettingsHandler) GetSecurityStatus(w http.ResponseWriter, r *http.Request) {
	status := SecurityStatus{}

	// Check NATS MQTT password.
	if v := os.Getenv("NATS_MQTT_PASSWORD"); v != "" && v != "changeme" {
		status.NATSMQTTAuth = true
	}

	// Check NATS leafnode token.
	if v := os.Getenv("NATS_LEAFNODE_TOKEN"); v != "" {
		status.NATSLeafAuth = true
	}

	// Check Redis password.
	if v := os.Getenv("REDIS_PASSWORD"); v != "" && v != "changeme" {
		status.RedisAuth = true
	}

	// Check if secrets were auto-generated.
	if _, err := os.Stat(serviceEnvFile); err == nil {
		status.AutoGenerated = true
		status.SecretsFilePath = serviceEnvFile
	}

	// Check stunnel mTLS (look for the config file with verify=2).
	if data, err := os.ReadFile("/etc/stunnel/reticulum.conf"); err == nil {
		if strings.Contains(string(data), "verify = 2") {
			status.StunnelMTLS = true
		}
	}

	writeJSON(w, http.StatusOK, status)
}

// serviceEnvFile is where rotated NATS/Redis service passwords are written;
// the compose stack sources it on restart.
const serviceEnvFile = "/data/secrets/.secrets.env"

// RotateServicePasswords generates new passwords for NATS and Redis,
// writes them to the secrets file, and returns instructions to restart.
// @Summary Rotate service passwords
// @Description Generates new NATS MQTT, leafnode, and Redis passwords. Requires service restart to take effect.
// @Tags settings
// @Produce json
// @Success 200 {object} map[string]string
// @Failure 500 {object} map[string]string
// @Router /api/settings/security/rotate [post]
func (h *SecuritySettingsHandler) RotateServicePasswords(w http.ResponseWriter, r *http.Request) {
	newNATS := generateHexPassword(32)
	newLeaf := generateHexPassword(32)
	newRedis := generateHexPassword(32)

	content := "# Rotated service passwords\n"
	content += "NATS_MQTT_PASSWORD=" + newNATS + "\n"
	content += "NATS_LEAFNODE_TOKEN=" + newLeaf + "\n"
	content += "REDIS_PASSWORD=" + newRedis + "\n"
	content += "HUB_MQTT_BROKER_URL=tcp://meshsat:" + newNATS + "@nats:1883\n"
	content += "HUB_NATS_URL=tcp://meshsat:" + newNATS + "@nats:1883\n"
	content += "HUB_REDIS_URL=redis://:" + newRedis + "@redis:6379/0\n"

	if err := os.WriteFile(serviceEnvFile, []byte(content), 0600); err != nil {
		writeError(w, http.StatusInternalServerError, "failed to write secrets: "+err.Error())
		return
	}

	slog.Info("service passwords rotated", "by", r.RemoteAddr)

	writeJSON(w, http.StatusOK, map[string]string{
		"status":  "rotated",
		"message": "New passwords written. Restart all services: docker compose restart nats redis hub-1 hub-2",
	})
}

func generateHexPassword(bytes int) string {
	b := make([]byte, bytes)
	if _, err := rand.Read(b); err != nil {
		return "fallback-" + hex.EncodeToString(b[:8])
	}
	return hex.EncodeToString(b)
}
