apiVersion: v1
kind: Namespace
metadata:
  name: meshsat-hub
  labels:
    app.kubernetes.io/part-of: meshsat-hub
---
apiVersion: v1
kind: Namespace
metadata:
  name: meshsat-hub-db
  labels:
    app.kubernetes.io/part-of: meshsat-hub
