apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nats-secrets
  namespace: meshsat-hub
  labels:
    app.kubernetes.io/name: nats
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: nats-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: NATS_MQTT_PASSWORD
      remoteRef:
        key: ci-no/apps/meshsat-hub/nats
        property: NATS_MQTT_PASSWORD
