package oob

import (
	"bytes"
	"encoding/hex"
	"testing"
)

// Spec section 15 vectors, generated by the bridge's reference implementation.
// A codec change that alters any of them breaks the bridge compatibility.
var vectorKey, _ = hex.DecodeString("0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20")

func TestVectors(t *testing.T) {
	if got := PeerIDFromKey(vectorKey); got != 38091 {
		t.Fatalf("peer id = %d, want 38091", got)
	}
	cases := []struct {
		name string
		f    Frame
		role Role
		wire string
		text string
	}{
		{"ping clear", Frame{PeerID: 38091, Counter: 1, Cmd: CmdPing}, RoleIssuer,
			"4f1094cb000000010128e6ae237647d91bef76e2429de0af78", "MS:9W899JR000002098WTQ26XJ7V4DYYXQ28AEY1BVR"},
		{"ping enc", Frame{Enc: true, PeerID: 38091, Counter: 2, Cmd: CmdPing}, RoleIssuer,
			"4f1194cb00000002018666a2f9108437f2059a6879bec7b958", "MS:9W8S9JR0000040C6CTHFJ4446ZS0B6K8F6ZCFEAR"},
		{"reboot enc", Frame{Enc: true, PeerID: 38091, Counter: 3, Cmd: CmdReboot, Args: EncodeRebootArgs(10)}, RoleIssuer,
			"4f1194cb0000000302b7f0ad66ee0a284af7d6cd03005693087802", "MS:9W8S9JR0000060NQY2PPDVGA515FFNPD0C05D4R8F010"},
		{"reply ok", Frame{Enc: true, Reply: true, PeerID: 38091, Counter: 1, Cmd: CmdReboot,
			Args: EncodeReplyArgs(ReplyArgs{RC: RCOK, ReqCounterLo: 3, Seq: 1, Total: 1, Body: []byte("rv10s")})}, RoleImporter,
			"4f1394cb0000000102d93a58b0698eef7c985c5067be26dcd4e381e72884a0a43b79ad", "MS:9W9S9JR0000020PS79CB0TCEXXY9GQ2GCYZ2DQ6MWE0YEA44M2J3PYDD"},
	}
	for _, c := range cases {
		wire, err := Seal(c.f, vectorKey, c.role)
		if err != nil {
			t.Fatalf("%s: seal: %v", c.name, err)
		}
		if got := hex.EncodeToString(wire); got != c.wire {
			t.Errorf("%s: wire %s, want %s", c.name, got, c.wire)
		}
		if got := Encode(wire); got != c.text {
			t.Errorf("%s: text %s, want %s", c.name, got, c.text)
		}
		back, err := Decode(c.text)
		if err != nil || !bytes.Equal(back, wire) {
			t.Errorf("%s: decode mismatch: %v", c.name, err)
		}
		f, err := Open(wire, vectorKey, c.role)
		if err != nil {
			t.Fatalf("%s: open: %v", c.name, err)
		}
		if f.PeerID != c.f.PeerID || f.Counter != c.f.Counter || f.Cmd != c.f.Cmd || f.Reply != c.f.Reply || !bytes.Equal(f.Args, c.f.Args) {
			t.Errorf("%s: open = %+v, want %+v", c.name, f, c.f)
		}
		// Opened with the wrong sender role the tag must not verify.
		if _, err := Open(wire, vectorKey, c.role.Other()); err == nil {
			t.Errorf("%s: opened with the wrong role", c.name)
		}
	}
	// Reflection: the first vector with the REPLY flag set fails authentication.
	wire, _ := hex.DecodeString(cases[0].wire)
	wire[1] = 0x12
	if _, err := Open(wire, vectorKey, RoleIssuer); err == nil {
		t.Errorf("reflected frame accepted")
	}
}

func TestExtractFrame(t *testing.T) {
	text := "MS:9W899JR000002098WTQ26XJ7V4DYYXQ28AEY1BVR"
	wire, ok := ExtractFrame("[tesseract] " + text + " end")
	if !ok || hex.EncodeToString(wire) != "4f1094cb000000010128e6ae237647d91bef76e2429de0af78" {
		t.Fatalf("extract: %v %x", ok, wire)
	}
	if _, ok := ExtractFrame("SMS:9W899JR000002098WTQ26XJ7V4DYYXQ28AEY1BVR"); ok {
		t.Errorf("SMS: prefix must not match")
	}
	if _, ok := ExtractFrame("hello from the field"); ok {
		t.Errorf("plain text matched")
	}
	if _, ok := ExtractFrame("ms:9w899jr000002098wtq26xj7v4dyyxq28aey1bvr"); !ok {
		t.Errorf("lower-case frame not matched")
	}
}

func TestReplayWindow(t *testing.T) {
	var w Window
	if !w.Accept(1) || w.Accept(1) {
		t.Fatalf("first accept / replay")
	}
	if !w.Accept(10) || w.Accept(10) || !w.Accept(5) || w.Accept(5) {
		t.Fatalf("out-of-order inside the window")
	}
	if w.Accept(0) {
		t.Fatalf("counter 0 accepted")
	}
	if !w.Accept(100) || w.Accept(30) {
		t.Fatalf("far behind the window accepted")
	}
	high, bits := w.State()
	var w2 Window
	w2.Load(high, bits)
	if w2.Accept(100) || !w2.Accept(101) {
		t.Fatalf("state round trip")
	}
}
