apiVersion: v1
kind: ServiceAccount
metadata:
  name: meshsat-hub
  namespace: meshsat-hub
  labels:
    app.kubernetes.io/name: meshsat-hub
imagePullSecrets:
  - name: registry-meshsat
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meshsat-hub
  namespace: meshsat-hub-db
  labels:
    app.kubernetes.io/name: meshsat-hub
imagePullSecrets:
  - name: registry-meshsat
